[package]
name = "httpwg-gen"
version = "0.1.0"
edition = "2021"
description = "Generates httpwg-macros from rustdoc's JSON output"
publish = false

[dependencies]
serde = { version = "1.0.206", features = ["derive"] }
serde_json = "1.0.122"
merde_json = "2.1.2"
